modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU AGPL 3.0"

[[mods]]
modId = "artiferrium"
version = "${version}"
displayName = "artiferrium"
authors = "VI Software"
description = '''
Artiferrium is one of the main server agents we provide to help sync and manage server artifacts
'''
#logoFile = ""

[[dependencies.artiferrium]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.artiferrium]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.artiferrium]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
